name: CD - Deploy to VM

on:
  workflow_run:
    workflows:
      - CI - Build and Push Docker Images
    types:
      - completed
    branches:
      - cloud-si-separation

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on VM via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: 46.101.134.200
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            set -e
            cd /aleksandar/app
            docker compose pull
            docker compose up -d --remove-orphans --force-recreate
            docker image prune -f